### ISSUE TITLE
Terminal state - Cartpole (two_poles) swing up

### ISSUE THREAD

**Issue by camontblanc** [deepmind/dm_control#103]
Hi!

I'm trying to do the `cartpole` domain, specifically the `two_poles`- swingup task. As said in the [tech report](https://arxiv.org/pdf/1801.00690.pdf), Control Suite tasks have no terminal states or time limit and are therefore of the infinite-horizon variety; however, I'd like to know when does this task end or, in other words, when does `time_step.last() == True` so that I can know the episode is over?

Thanks!

**Comment by alimuldal** [comment]
All environments in the control suite have built-in time limits (e.g. for cartpole the time limit is [10 seconds per episode](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/cartpole.py#L35)). For the control suite the time limit and the control time step are set such that each episode lasts for exactly 1000 steps.

This is not guaranteed for environments outside the control suite, though - in general episodes can terminate at any time, either due to hitting an internal time limit or entering a terminal state. The correct way to test whether an episode has terminated is to check whether `time_step.last() == True`, as you're currently doing.
