### ISSUE TITLE
Indexing result of inverse kinematics

### ISSUE THREAD

**Issue by YeeCY** [deepmind/dm_control#124]
I found the IKResult.qpos in [inverse_kinematics.py](https://github.com/deepmind/dm_control/blob/f5b83df2df4f0053f0cc4a195d6dd9d94ea1edf1/dm_control/utils/inverse_kinematics.py#L89) is a numpy array. Thus, I cannot index it by joint names as FieldIndex wrapped objects. Any suggestions or solutions?

**Comment by alimuldal** [comment]
You can use the row indexer for `physics.named.data.qpos` to compute a set of indices corresponding to the joint name(s) you are interested in, then use these to index into `result.qpos`, e.g.:
```python
indices = physics.named.data.qpos.axes.row.convert_key_item(joint_names)
result.qpos[indices]
```
This is essentially what we do [here](https://github.com/deepmind/dm_control/blob/f5b83df2df4f0053f0cc4a195d6dd9d94ea1edf1/dm_control/utils/inverse_kinematics.py#L149-L155) in order to compute indices into the Jacobian array that correspond to particular named joints.
