### ISSUE TITLE
use openai gym mujoco xml files in physics

### ISSUE THREAD

**Issue by xinleipan** [deepmind/dm_control#126]
Can I directly initialize an environment not by using the xml files provided in this repo but from openai gym's mujoco xml files? Will there be any discrepancy?

**Comment by alimuldal** [comment]
No, you'd almost certainly need to edit the Gym XML files and/or the `Task` classes in `dm_control/suite` in order to make them work together. One reason is that each task implementation will reference specific elements in the corresponding XML file (usually by its name) - for example we often use the positions or velocities of particular bodies or joints in the model in order to compute the reward for each timestep. The tasks won't work unless the corresponding elements are also present in the Gym XML files.
