### ISSUE TITLE
why is the state from physics different from the state from time_step?

### ISSUE THREAD

**Issue by xinleipan** [deepmind/dm_control#127]
I'm trying two ways of getting states from a "control" environment. So I created an environment using suite, for example 

`env = suite.load(domain_name="cartpole", task_name="swingup")`, 

and 

`time_step=env.reset()`

, then I can get state either by 

`obs = time_step.observation`

 or by 

`env._physics.get_state()`

which one is the better one? If I want to use vision based control, can I call 
`env._physics.render()`

to get the observation?

**Comment by alimuldal** [comment]
There's a distinction between "states" and "observations" - see Section 2 in our [tech report](https://arxiv.org/pdf/1801.00690.pdf).

`physics.get_state()` returns MuJoCo's internal representation of the physics state, which consists of raw joint positions, velocities, and actuator states. `timestep.observation` contains an observation whose features are _derived_ from the current state of the simulation, but not necessarily identical to it. In general we try to pick features that are easier to interpret and to train policies from than just the raw physics state. For example we typically use sine, cosine pairs rather than raw angles to represent the positions of unbounded rotational joints, since that way the feature values are continuous and bounded between -1 and 1.

All environments in the control suite (with the exception of `point_mass.hard`) are fully observable, meaning that a single observation is sufficient to completely describe the state of the environment. However this is not necessarily true of environments in general - for example, environments with pixel-only observations are often not fully observable due to lack of velocity information, occlusions etc.
