### ISSUE TITLE
Question - Discount factor.

### ISSUE THREAD

**Issue by moonsh** [deepmind/dm_control#143]
I read the below description. And wonder why you set the discount factor like this. Could you give more explanation? I couldn't find an explanation about this in the paper. 
If an agent scores a goal, only the action just before scoring a goal is rewarded?

- EMERGENT COORDINATION THROUGH COMPETITION -
Episodes will terminate immediately with a discount factor of 0 when either side scores a goal. There is also a per-episode time_limit (45 seconds by default). If neither team scores within this time then the episode will terminate with a discount factor of 1.

**Comment by alimuldal** [comment]
I was not an author on this paper, but I can try to give some intuition.

Terminating an episode with a discount factor of 0 means that _only_ the immediate reward given on the final timestep should be taken into account when estimating the value of the final state, not any (possibly rewarding) future states that could be reached from there. This effectively breaks the game up into the periods of play in between goals. From an agent's perspective it is as though the game ends the moment a goal is scored (a bit like the "[golden goal]" rule for extra time), and then a completely new game begins. In this framing of the RL problem the objective that agents should optimize is to score a goal as quickly as possible without conceding one.

It might be helpful to think about other ways in which you could frame soccer as an RL problem.  For example you could imagine having the teams play against each other for some fixed period of time, and then give a reward of +1 to whichever team scored the most goals and -1 to the losers (or 0, 0 if it was a draw). Arguably this would be closer to a real soccer match, but then credit assignment would be _much_ harder, since all of the actions taken over the course of the entire game can potentially contribute to the outcome, rather than just the actions since the last goal was scored.

I suspect the reason for truncating the episodes at 45 seconds is so that agents see a more diverse set of initial states, since the pitch will be randomized in between episodes. The reason for terminating with a discount of 1 rather than 0 is because in this case we _do_ want potential future rewards to be taken into account when estimating the value of the final state. For example, suppose one of the players has just kicked the ball towards the opponent's goal, but just before the ball can cross the goal line the episode ends due to the time limit. The value of the state where the ball is just about to cross the goal line should be high because it is close to a rewarding state, even though no immediate reward has been given _yet._

[golden goal]: https://en.wikipedia.org/wiki/Golden_goal
