### ISSUE TITLE
Training Jaco reach duplo features environment

### ISSUE THREAD

**Issue by melfm** [deepmind/dm_control#154]
Hello, I am trying to train a policy using the jaco manipulation environment and I have a few questions with regards to the environment setup:

- The current implementation seems to be using a position controller to send the arm to the home position, and the agent is learning a velocity controller. I was wondering if this can make the task of an RL agent harder? Specially when learning from pixel observations. Did you try training any algorithm with this env?
- Do you have plans on adding either an end-effector controller that is typically used in other robotic arm manipulation tasks?

@alimuldal Tagging you here since you seem to be the author for this code.

Thanks in advance!

**Comment by alimuldal** [comment]
Hi, I'm sorry for the very late response

* It's not really a position controller per se - when we randomly initialise the arm position at the start of an episode we run IK to find a set of joint positions that satisfy the sampled end effector position, and then just set the arm joint positions directly [using `inplace=True`](https://github.com/deepmind/dm_control/blob/abf17cc53c97e3bef9b0a28cb9d817cf94318b11/dm_control/utils/inverse_kinematics.py#L42), rather than applying torques and running the simulation forward in order to drive it to the desired position.
* I don't have any immediate plans to implement end effector position control (I'm no longer actively developing this code, as I've since moved on to other projects). End effector position control would probably make some of the tasks easier to solve (certainly the `reach` and `lift` ones), although I suspect that's probably not true of all of the tasks. For example `lift_large_box` is likely to benefit from more direct control over the arm joint position since the agent needs to grasp the box using its whole arm rather than just the fingers.
* Yes, we have trained agents to solve the `reach` tasks (for example D4PG, MPO). `reach_site_features` and `reach_lego_features` are mostly used for debugging purposes since they are quite easy to solve from state, even with velocity control. If you're struggling then I suspect you may have a bug in your agent.
