### ISSUE TITLE
Contact Full error in CMU Humanoid Run

### ISSUE THREAD

**Issue by varun-intel** [deepmind/dm_control#155]
I'm hitting the following error when I try to use the CMU Humanoid run environment. The error pops up after several hours of training.

  File "/dmc2gym/dmc2gym/wrappers.py", line 159, in reset
    time_step = self._env.reset()
  File "/usr/local/lib/python3.6/dist-packages/dm_control/rl/control.py", line 89, in reset
    self._task.initialize_episode(self._physics)
  File "/usr/local/lib/python3.6/dist-packages/dm_control/suite/humanoid_CMU.py", line 140, in initialize_episode
    physics.after_reset()
  File "/usr/local/lib/python3.6/dist-packages/dm_control/mujoco/engine.py", line 299, in after_reset
    self.forward()
  File "/usr/local/lib/python3.6/dist-packages/dm_control/mujoco/engine.py", line 309, in forward
    mjlib.mj_forward(self.model.ptr, self.data.ptr)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/dm_control/mujoco/engine.py", line 332, in check_invalid_state
    raise _control.PhysicsError(message)
dm_control.rl.control.PhysicsError: Physics state is invalid. Warning(s) raised: mjWARN_CONTACTFULL

**Comment by yuvaltassa** [comment]
So there are two answers to this.

1. This just happens, rarely. Discard the episode and move on. A complicated model like CMU humanoid will diverge sometimes. Remember that the timestep size is always selected to be as big as possible (for simulation speed and learning speed) but not so big that the sim diverges often. So just on the limit of stability is where you want to be. You could completely solve this by using a tiny timestep, but better to just ignore the occasional divergence and have a faster model.

2. This can happen "less rarely" with agent training (as opposed to random actions). This is because agents often learn to exploit the simulator's inaccuracy (resulting from the time discretisation) and actually make the simulation diverge "on purpose". This will usually look like aggressive flapping of small bodies (e.g. hands), since these are harder to simulate due to their small mass. So the agent can sometimes learn to "suck energy out of the integrator". This is something you can solve by decreasing the timestep or adding damping/armature to you joints, but this of course this will change the model somewhat.

In general I should add that the CMUhumanoid was not really designed for RL from scratch, those example tasks are too underspecified and you're sure to get weird looking solutions. The point of the CMUhumanoid is that it comes with the mocap dataset which you're supposed to use as a prior for learning (see e.g. [this paper](https://arxiv.org/abs/1811.11711)). This motion prior will of course also solve issue #2 above, since there is no crazy hand flapping in the mocap data :-)
