### ISSUE TITLE
expected LP_MJMODEL instance instead of MjModel

### ISSUE THREAD

**Issue by kracon7** [deepmind/dm_control#168]
Hi,
I had an error while using functions from ```mjlib```
Here's an example:
```
>>> from dm_control.mujoco.wrapper.mjbindings import mjlib
>>> H=np.zeros(sim.model.nv * sim.model.nv)
>>> mjlib.mj_fullM(sim.model, H, sim.data.qM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_MJMODEL instance instead of MjModel
```

Could anyone tell me which object should I input for the first argument? Thanks a lot!

**Comment by alimuldal** [comment]
You want `model.ptr` rather than `model`. `model.ptr`, `data.ptr` etc. expose `ctypes` pointers to the underlying C structs, which you can pass to the wrapped `libmujoco` functions in `mjlib` - for example see [here](https://github.com/deepmind/dm_control/blob/master/dm_control/mujoco/engine.py#L163).
