### ISSUE TITLE
Cannot install package dm-tree in raspbian os.

### ISSUE THREAD

**Issue by neeraj-partha** [deepmind/dm_control#179]
'pip install dm-tree' hangs forever on Raspberry pi 3 (armv7l) with Raspbian buster OS. can you please help.
Thanks

**Comment by alimuldal** [comment]
This is an issue with [`dm-tree`](https://github.com/deepmind/tree) rather than `dm_control`, so you should raise it there instead. `dm-tree` does not offer precompiled wheels for ARM (related issue: https://github.com/deepmind/tree/issues/18, although in your case you'd need a 32 bit rather than a 64 bit binary). It may be possible to cross-compile `dm-tree` for ARM - you'd need to ask the `dm-tree` maintainers how to do this, though.
