### ISSUE TITLE
Physics.set_state not setting angle?

### ISSUE THREAD

**Issue by cagatayyildiz** [deepmind/dm_control#181]
Hi, 

I'm trying to set the CartPole state as follows. When I compare the newly set state and the input state, it looks all fine.
```
import numpy as np
from dm_control import suite
env = suite.load(domain_name='cartpole', task_name='swingup')
# cart_pos, th, cart_vel, pole_vel
input_state = np.array([ 1.234, 2.345, -3.456, 4.567], dtype=np.float64)
env.physics.set_state(input_state)
print(env.physics.state() - input_state) # all zeros
```

But then when I try to get the observations as follows,  
```
env._task.get_observation(env._physics)
```
the output becomes
```
OrderedDict([('position', array([1.234, 1.   , 0.   ])), ('velocity', array([-3.456,  4.567]))])
```
In other words, the angle observations (and only they) are wrong. Note that for any `input_state`, they are always `[1,0]`. 

May there be a bug or do I call wrong functions for some reason?

Thanks!

**Comment by alimuldal** [comment]
The cart position is read directly from `qpos` (the joint positions in generalized coordinates), which gets updated immediately when you set the state of the simulation. However the sine and cosine of the pole angle are [derived from `xmat`](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/cartpole.py#L148) (the rotation matrix in world coordinates), which is not part of the underlying simulation state, but rather an intermediate result derived from the state during the [forward dynamics pass](http://www.mujoco.org/book/programming.html#siForward). Normally it would get recalculated during the next call to [`physics.step`](https://github.com/deepmind/dm_control/blob/master/dm_control/mujoco/engine.py#L149), however here you're just setting the state without stepping, so it hasn't had a chance to be updated yet.

You can manually recompute the forward dynamics without advancing the simulation state by calling `physics.forward()`. If you do this and then recompute the observations using `env._task.get_observation(env._physics)` then you'll see that the angular position observations have been updated (note that they're the sine and cosine rather than the raw joint angle).
