### ISSUE TITLE
Cannot set device_id for headless GPU rendering

### ISSUE THREAD

**Issue by Kelly510** [deepmind/dm_control#185]
I am using dm_control for headless GPU rendering for mujoco. My target is to set an argument like device_id in mujoco_py but found out there is no such argument in render() in dm_control. Without this argument, the training is very slow as rendering and training share the same GPU.
Wondering how can I set a different GPU for rendering from that for training.

**Comment by alimuldal** [comment]
If you are using the EGL backend you can set the `EGL_DEVICE_ID=` environment variable to control which device will be used for rendering. This needs to be set before you import the MuJoCo bindings (initializing a device is expensive, so that's not something you'd want to do per call to `render`). https://github.com/deepmind/dm_control#rendering
