### ISSUE TITLE
Training time compare to PyBullet

### ISSUE THREAD

**Issue by IanWangg** [deepmind/dm_control#193]
Hi all, I am new to the dm_control suite. I am doing transfer learning on dm_control since it provides different tasks for a same robot. However, I found that it takes way longer time to train an agent on 'hopper-hop' than on 'Hopper-V2'. Usually, td3 can converge within 1e6 steps on 'Hopper-V2', but it still performs very poorly on 'hopper-hop' after the same amount of steps, what is the intuition behind this? Aren't 'hopper-hop' and 'Hopper-V2' similar kind of problem?

**Comment by alimuldal** [comment]
They are superficially similar, but `hopper` in the Control Suite is a much harder task by design, mainly because it has a lot more variability in the initial state between episodes.

In `HopperV2` [a tiny amount of uniform noise](https://github.com/openai/gym/blob/a5a6ae6bc0a5cfc0ff1ce9be723d59593c165022/gym/envs/mujoco/hopper.py#L31-L32) is added to the joint positions and velocities, whereas in [`hopper`](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/hopper.py#L106) we sample the initial position of each hinge joint [uniformly between its limits](https://github.com/deepmind/dm_control/blob/892b4e4e298825e86cd0364619bf4e36258f71d2/dm_control/suite/utils/randomizers.py#L69):

![image](https://user-images.githubusercontent.com/2284074/125355113-869f1100-e35c-11eb-93a3-7b89491d2e38.png)
(I don't have a copy of Gym installed that I can easily compare to, but if you do the same you'll see that with `Hopper-v2` the initial configuration is much less varied)

Increasing the variability in the initial states makes learning more difficult, but also tends to result in policies that are more robust to perturbations. There are also differences in the reward functions and episode durations that may contribute, but I suspect it's the initial state randomization that accounts for most of the difference you're seeing.
