### ISSUE TITLE
Changing the size of objects in control suite

### ISSUE THREAD

**Issue by alexoshin** [deepmind/dm_control#231]
Is it possible to change the size or shape of an object while the sim is running without creating an entirely new physics environment? For example, changing the length of the cartpole pole between calls to physics.step()?

The closest I've gotten is initializing a new physics object by editing the XML but the behavior doesn't seem as intended and is painfully slow.

Any help would be appreciated. Thanks!

**Comment by yuvaltassa** [comment]
Hi,

This is possible for some things (e.g. mass) by modifying the `Physics.model` directly. Changing sizes is also possible but trickier, since you need to familiarise yourself with MuJoCo's compilation process (e.g. you might need to also increase `geom_rbound` etc).

Recreating the XML is indeed the recommended thing, and precisely what the [PyMJCF](https://github.com/deepmind/dm_control/blob/master/dm_control/mjcf/README.md) library, was designed to do. However we only use it at init, not at runtime. Recreating the XML at runtime should be fine if it happens only rarely. If it happens often it will indeed be slow, but should behave correctly.
