### ISSUE TITLE
potentially wrong condim in humanoid xml in the branch "merel_2017_humanoid"

### ISSUE THREAD

**Issue by WilsonWangTHU** [deepmind/dm_control#28]
Hi guys,
Thanks so much for sharing the CMU humanoid used in Merel et al 2017 (and making a new branch accordingly).

But I am not sure why you guys set the condim to be 1 in line 11 in dm_control/suite/humanoid_CMU.xml.
According to mojuco's modeling doc, "
1 | Frictionless contact.
3 | Regular frictional contact, opposing slip in the tangent plane.
4 | Frictional contact, opposing slip in the tangent plane  and rotation around the contact normal. This is useful for modeling soft  contacts (independent of contact penetration).
6 | Frictional contact, opposing slip in the tangent plane,  rotation around the contact normal and rotation around the two axes of  the tangent plane. The latter frictional effects are useful for  preventing objects from indefinite rolling.
"

I believe condim should always be fixed to 3, otherwise you get something like this: 
https://youtu.be/c0qgCsXuLYo

thanks in advance
best regards

**Comment by alimuldal** [comment]
Fixed in 4d805f194bb60544ec27cfeccd7d92235e7831e2

`condim="1"` was incorrectly being used as a global default, rather than just for the `"humanoid"` default class. The intent was to use `condim="3"` for the floor and `condim="1"` for the humanoid. For contacts between geoms with different condims [MuJoCo uses the pairwise maximum][1], so humanoid-floor contacts will have sliding friction, but humanoid-humanoid contacts will be frictionless (for efficiency).

[1]: http://www.mujoco.org/book/computation.html#coParameters
