### ISSUE TITLE
How many time steps are needed to see the action achieved?

### ISSUE THREAD

**Issue by lisayan** [deepmind/dm_control#29]
For example, in the README example with cartpole and swingup, I do not see the action achieved with 10 time steps. Do you have any documentation on how long different tasks take, or at what time step the results in the Youtube video happened?

**Comment by alimuldal** [comment]
I'm not quite sure what you're asking. For cartpole, each timestep corresponds to [10 ms of simulation time][cartpole_sim_timestep]. The simulation timestep differs across tasks - you can find it by looking for `<option timestep=... />` in the corresponding XML file.

Also, note that the example code in the README uses uncorrelated uniform noise for the actions. Since the sign of the action varies randomly between timesteps, the actions will tend to cancel each other out, so the cartpole probably won't move very much (although you should still see `time_step.observation` and `time_step.reward` changing between steps). You definitely shouldn't expect to see anything like the behaviour in the YouTube video, which was generated using a policy trained to solve the task from observations rather than just random actions.

 Does that answer your question?

[cartpole_sim_timestep]: https://github.com/deepmind/dm_control/blob/master/dm_control/suite/cartpole.xml#L6

**Comment by lisayan** [comment]
Oh yes that makes sense, sorry I missed it! Is there an explicit example of any policies that you have trained?

**Comment by lisayan** [comment]
Yes, thank you!
