### ISSUE TITLE
How to change color of JumpingBall mid-episode?

### ISSUE THREAD

**Issue by alexzhou907** [deepmind/dm_control#296]
I have a jumping ball instance as in[ jumping_ball.py ](https://github.com/deepmind/dm_control/blob/4e1a35595124742015ae0c7a829e099a5aa100f5/dm_control/locomotion/walkers/jumping_ball.py#L28)that reads in an .xml file with texture field like
`<texture name="body" type="cube" builtin="checker" rgb1="1.0 .1 .1" rgb2=".5 0.1 0.5" width="100" height="100"/>`. I attempt to change the rgb1 and rgb2 mid-episode by directly accessing the fields by
```
    self._mjcf_root.find('texture', 'body').rgb1 = np.array(new_rgb1)
    self._mjcf_root.find('texture', 'body').rgb2 = np.array(new_rgb2)
```
But this doesn't actually change the color. How can this be done?

**Comment by yuvaltassa** [comment]
After compilation (e.g. mid episode) you'd need to modify the compiled model directly. This can be unsafe for many properties but for rgba it's totally fine. Somewhere where you have access to the `physics` object you can do `physics.model.geom_rgba[geom_id, :] = rgba` or `physics.named.model.geom_rgba[geom_name, :] = rgba`.

If you want to modify textures rather than geom rgba's you'd need to directly change the pixel values in `model.tex_rgba`, but I'd only try that if you literally want to change what's painted on the object, for global colour use `geom_rgba`.

**Comment by kevinzakka** [comment]
@alexzhou907 You're missing a `bind` call to your found elem:

```python
body = self._mjcf_root.find('texture', 'body')
physics.bind(body).rgb1 = np.array(new_rgb1)
physics.bind(body).rgb2 = np.array(new_rgb2)
```

Note if the color is fixed, you don't need to create a new numpy array so it'll save you an extraneous copy.
