### ISSUE TITLE
protobuf version conflict with tensorflow

### ISSUE THREAD

**Issue by NgChucky** [deepmind/dm_control#339]
Tensorflow 2.9.1 requires protobuf<=3.20.0 but dm_control requires protobuf>=3.20.1. How does deepmind internally even work on their AI systems with this going on? I don't understand.

**Comment by saran-t** [comment]
Looks like the the `protobuf<3.20` requirement in TensorFlow is there because of a link error that only exists on Windows https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L88

Internally, we share [a monorepo](https://dl.acm.org/doi/pdf/10.1145/2854146) with Google, which means that first-party like `tensorflow`, `dm_control`, and `protobuf` are kept compatible with each other "at HEAD", rather than with specific versions. (In short, we don't rely on Git or PyPI packages.)

I'll lower the `protobuf` version requirement in `dm_control` for our next release (which will hopefully come out this week).
