### ISSUE TITLE
Position and velocity in cheetah environment

### ISSUE THREAD

**Issue by rajcscw** [deepmind/dm_control#42]
Why is the position in cheetah is of dim 8 but the velocity is of dim 9? And what do they denote?
Are they 3d position of joints? Documentation of observation for all the environments would be very helpful in general.

**Comment by alimuldal** [comment]
The position and velocity observations are defined here: https://github.com/deepmind/dm_control/blob/master/dm_control/suite/cheetah.py#L93-L95. `physics.data.qpos` is an array containing the positions of all the joints in the model in the order that they are declared in `cheetah.xml`. `physics.velocities()` returns an array containing the velocities of all of the joints.

The first joint is a horizontal slide joint which allows the torso of the cheetah to move backwards and forwards: https://github.com/deepmind/dm_control/blob/master/dm_control/suite/cheetah.xml#L29. We include the velocity of this joint in the observation but not its position because we want the observations to be invariant to horizontal translation, hence why there are 9 velocity elements but only 8 position elements.
