### ISSUE TITLE
Scale of observation space

### ISSUE THREAD

**Issue by rajcscw** [deepmind/dm_control#43]
Is there a possibility to get the max and min of observations. This would be very helpful in scaling the observations before feeding to the networks. We can add this to `env.observation_spec()` ? Another possibility would be provide `env.observation_samples()` which provide some sample data points so that the user can fit a scaler object.

**Comment by danijar** [comment]
This would especially be useful for learning dynamics models, which are often sensitive to scaling.

**Comment by alimuldal** [comment]
We can't provide observation bounds in the general case, since some types of observation are unbounded (such as velocities). One way to deal with differing observation scales is to keep a running estimate of the mean and STD of your raw observations and then normalizing them by subtracting the mean and dividing by the STD (such as in https://arxiv.org/abs/1707.02286).
