### ISSUE TITLE
get camera information in viewer?

### ISSUE THREAD

**Issue by Xingyu-Lin** [deepmind/dm_control#71]
Is there any way to get the pos and quaternion of the free camera in the viewer? Only the statically defined camera can be seen in physics.model.cam_pos

**Comment by yuvaltassa** [comment]
This is the `dump camera` option mentioned in the onscreen help available under `F1`. It is currently bound to the `F11` key. Look at the code around line 240 in `viewer.py` to see what is being accessed. Note that for camera orientations, the frame's _x_ and _y_ axes corresponds to _right_ and _up_ (in pixel space), respectively.

If you need a quat rather than a rotation matrix you'll want to call MuJoCo's `mju_mat2Quat()` or similar function.
