### ISSUE TITLE
Version of MuJoCo Pro

### ISSUE THREAD

**Issue by psguo** [deepmind/dm_control#8]
Can I use Mujoco v1.31 as physics engine?

I am using rllab (https://github.com/rll/rllab) framework to implement my algorithm. It requires Mujoco v1.31 but dm_control uses Mujoco v1.50.

**Comment by yotam** [comment]
Unfortunately not. There are some [renames and other API changes](http://www.mujoco.org/changelist.html) between these versions of MuJoCo.

While the wrapper generation may work, the code in dm_control/mujoco assumes we're using MuJoCo 1.50. For example, it uses `mj_saveLastXML` instead of `mj_saveXML`, `mjv_select` instead of `mjr_select`, and so on.
