### ISSUE TITLE
Make dm_control available on PyPI

### ISSUE THREAD

**Issue by zuoxingdong** [deepmind/dm_control#90]
It'll be very convenient to support pip installation via PyPI

**Comment by alimuldal** [comment]
`dm_control` can be installed using `pip` by passing the address to our Github repository:
```bash
pip install git+git://github.com/deepmind/dm_control.git
```
Alternatively you could check out a local copy of `dm_control`, and then install it by path
```bash
pip install /path/to/dm_control
```
I suspect what you're really asking is whether we can host `dm_control` on PyPI  (so you could just do `pip install dm_control`)? We're looking into that, but there are some complications due to the fact that we auto-generate the ctypes bindings from the MuJoCo headers as part of the installation process.

**Comment by saran-t** [comment]
`dm_control` is now available on PyPI.
